### ISSUE TITLE
Can't build on fresh checkout

### ISSUE THREAD

**Issue by vitch** [CrowdStrike/ember-headless-table#160]
Running the following:

```
git clone https://github.com/CrowdStrike/ember-headless-table.git headless-table-test
cd headless-table-test
pnpm install
pnpm start
```

Results in an error:

```
[docs-app] ERROR in ./components/docfy-demo-demos-single-row-selection-demo-a.js 5:0-53
Module not found: Error: Can't resolve 'ember-headleBuild Error (PackagerRunner) in ../../../../../../../../../Applications/Code/OpenSource/headless-table-test/node_modules/.pnpm/css-loader@5.2.7_webpack@5.80.0/node_modules/css-loader/dist/cjs.js??ruleSet[1].rules[2].use[1]!/Applications/Code/OpenSource/headless-table-test/node_modules/.pnpm/postcss-loader@7.2.4_@types+node@18.15.11_postcss@8.4.22_ts-node@10.9.1_typescript@4.9.5_webpack@5.80.0/node_modules/postcss-loader/dist/cjs.js??ruleSet[1].rules[3].use[0]!/private/var/folders/_f/fd7qlbwn22l9jt9535y9p9bc0000gn/T/embroider/7bab5c/docs-app/assets/styles.css
[docs-app]
[docs-app] Module build failed (from ../../../../../../../../../Applications/Code/OpenSource/headless-table-test/node_modules/.pnpm/postcss-loader@7.2.4_@types+node@18.15.11_postcss@8.4.22_ts-node@10.9.1_typescript@4.9.5_webpack@5.80.0/node_modules/postcss-loader/dist/cjs.js):
[docs-app] Error: Cannot find module '/Applications/Code/OpenSource/headless-table-test/docs-app/node_modules/ember-headless-table/dist/index.js'
[docs-app]     at createEsmNotFoundErr (node:internal/modules/cjs/loader:1096:15)
[docs-app]     at finalizeEsmResolution (node:internal/modules/cjs/loader:1089:15)
[docs-app]     at resolveExports (node:internal/modules/cjs/loader:565:14)
[docs-app]     at Function.Module._findPath (node:internal/modules/cjs/loader:634:31)
[docs-app]     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1061:27)
[docs-app]     at Function.Module._resolveFilename.sharedData.moduleResolveFilenameHook.installedValue [as _resolveFilename] (/Applications/Code/OpenSource/headless-table-test/node_modules/.pnpm/@cspotcode+source-map-support@0.8.1/node_modules/@cspotcode/source-map-support/source-map-support.js:811:30)
[docs-app]     at Function.resolve (node:internal/modules/cjs/helpers:116:19)
[docs-app]     at /Applications/Code/OpenSource/headless-table-test/node_modules/.pnpm/@crowdstrike+ember-oss-docs@1.1.4_@babel+core@7.21.4_@crowdstrike+tailwind-toucan-base@3.4.0__ardyz2lvriqhfubpverz4mczku/node_modules/@crowdstrike/ember-oss-docs/tailwind.cjs:22:50
[docs-app]     at Array.map (<anonymous>)
[docs-app]     at tailwindConfig (/Applications/Code/OpenSource/headless-table-test/node_modules/.pnpm/@crowdstrike+ember-oss-docs@1.1.4_@babel+core@7.21.4_@crowdstrike+tailwind-toucan-base@3.4.0__ardyz2lvriqhfubpverz4mczku/node_modules/@crowdstrike/ember-oss-docs/tailwind.cjs:21:48)
[docs-app]
[docs-app]
[docs-app] Stack Trace and Error Report: /var/folders/_f/fd7qlbwn22l9jt9535y9p9bc0000gn/T/error.dump.36c6c9f090ddccf68cc14b5ea2d3454c.log
```

```
pnpm --version 
// 8.3.0 
node --version
// v18.16.0
```

**Comment by vitch** [comment]
This does work:

```
git clone https://github.com/CrowdStrike/ember-headless-table.git headless-table-test
cd headless-table-test
pnpm install
pnpm start
// Error then [Ctrl + C]
pnpm install --force
pnpm start
```

It seems like a `--force` install _after_ a `start` gets things into a good place??!?!
